import { defineStore } from 'pinia'

export const usePreferencesStore = defineStore('preferences', {
  state: () => ({
    preferLooseListItem: '',
    autoPairBracket: '',
    autoPairMarkdownSyntax: '',
    autoPairQuote: '',
    bulletListMarker: '',
    orderListDelimiter: '',
    tabSize: '',
    listIndentation: '',
    frontmatterType: '',
    superSubScript: '',
    footnote: '',
    isHtmlEnabled: '',
    isGitlabCompatibilityEnabled: '',
    lineHeight: '',
    fontSize: '',
    codeFontSize: '',
    codeFontFamily: '',
    codeBlockLineNumbers: '',
    trimUnnecessaryCodeBlockEmptyLines: '',
    editorFontFamily: '',
    hideQuickInsertHint: '',
    hideLinkPopup: '',
    autoCheck: '',
    editorLineWidth: '',
    imageInsertAction: '',
    imagePreferRelativeDirectory: '',
    imageRelativeDirectoryName: '',
    imageFolderPath: '',
    theme: '',
    sequenceTheme: '',
    hideScrollbar: '',
    spellcheckerEnabled: false,
    spellcheckerNoUnderline: '',
    spellcheckerLanguage: '',
    sourceCode: '',
    textDirection: '',
    zoom: 0,
    typewriter: '',
    focus: '',
  }),
})
